### ISSUE TITLE
Credit in Contribution.rst

### ISSUE THREAD

**Issue by Z-Fikar** [translate/l10n-guide#42]
Hi, I just read the [contributing.rst](https://github.com/translate/l10n-guide/blob/master/docs/guide/contributing.rst) and I saw this

>We :doc:\`credit <credits>\` those who contribute whole sections and
significatant update.

I am new to reStructuredText file and still learning but I'm not quite sure what are you trying to do with 
the **:doc:\`credit <credits>\`**. Is that supposed a link to [credits.rst](https://github.com/translate/l10n-guide/blob/master/docs/guide/credits.rst)? 

If yes then should it changes to  **\`credit <credits.rst>\`_** without **:doc:**?
If no, please explain it to me? 😅 is that **:doc:** supposed to be something?

**Comment by dwaynebailey** [comment]
@Z-Fikar first things first, is it broken? If not then assume its correct.

A quick .rst primer on links:

1. `:doc:` links to a whole document, as we're doing here.
2.  `xxx`_ is usually used for external links.
3.  `:ref:` can be used for internal links across the whole set of .rst file, sort of like a `#` tag in html.

**Comment by Z-Fikar** [comment]
How do you know if it is broken?
I try to click the **:doc\`credit<credits>\**
and it links to 
https://github.com/translate/l10n-guide/blob/master/docs/guide/contributing.rst#id1

I presume that, that is wrong and should be refer to
https://github.com/translate/l10n-guide/blob/master/docs/guide/credits.rst
`

**Comment by Z-Fikar** [comment]
Wait, when you said
>:doc: links to a whole document, as we're doing here.
Do you mean a document that not in this repo?

**Comment by jayvdb** [comment]
Here is another way to look at this:

This is a guide, written in `.rst` files.  The guide is built and published at http://docs.translatehouse.org/projects/localization-guide/en/latest/index.html .
If you go to the Contributing page, you will see it correctly links to the Credits page.

So, this is not a valid bug.  The file `.travis.yml` performs some checking of the RST file, and it does check for broken links in the rst files.  But there are are more detailed RST checkers available, which you could add to `.travis.yml` to reduce the chance of syntax or grammar bugs.
